# Generated by Django 2.1.2 on 2018-12-06 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Distances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_A', models.CharField(max_length=150, unique=True)),
                ('distance', models.IntegerField()),
            ],
            options={
                'db_table': 'Distances',
            },
        ),
        migrations.CreateModel(
            name='Maps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'Maps',
            },
        ),
        migrations.AddField(
            model_name='distances',
            name='map_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Maps'),
        ),
    ]
