# Generated by Django 2.1.2 on 2018-12-06 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_distances_point_b'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maps',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
