# Generated by Django 2.1.2 on 2018-12-06 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20181206_2331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distances',
            name='map_name',
        ),
    ]
