# Generated by Django 2.1.2 on 2018-12-07 02:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_distances_map_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='distances',
            old_name='point_A',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='distances',
            old_name='point_B',
            new_name='start',
        ),
        migrations.AddField(
            model_name='distances',
            name='map_name',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=None, to='api.Maps'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='maps',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
